### PR TITLE
material icon updates (outlined, round, sharp)

### PR DESCRIPTION
**Pull request by hawkeye64**
adding outlined, round and sharp

### CODE REVIEW

**Comment by hawkeye64** [comment]
I'd like to learn how to test this after changes made. I don't know how. :(

**Comment by hawkeye64** [comment]
Also, could not figure out how to use themify-icons via cdn - their main file does a lot of imports

**Comment by hawkeye64** [comment]
Outlined:
image
Round:
image
Sharp:
image
Fontawesome:
image
Ionicons:
image
MDI:
image
Evaicons:
image
Material Design:
image

**Comment by hawkeye64** [comment]
all fonts tested....

**Comment by rstoenescu** [comment]
Awesome work!

**Pull request merged**
